### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by catdevnull** [catdevnull/preciazo#35]
```
preciazo-scraper-1  | called `Result::unwrap()` on an `Err` value: error returned from database: (code: 5) database is locked
preciazo-scraper-1  | 
preciazo-scraper-1  | Caused by:
preciazo-scraper-1  |     (code: 5) database is locked
preciazo-scraper-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
preciazo-scraper-1  | thread 'tokio-runtime-worker' panicked at src/main.rs:118:25:
preciazo-scraper-1  | called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(15387), ...)
preciazo-scraper-1  | thread 'main' panicked at src/main.rs:471:10:
preciazo-scraper-1  | called `Result::unwrap()` on an `Err` value: task 10 panicked
```

**Comment by catdevnull** [comment]
vamos a ver si con https://github.com/catdevnull/preciazo/commit/cf52da7445ea7b2951b44feb478f48c5bd278452 se arregla

**Comment by catdevnull** [comment]
```
preciazo-scraper-1  | thread 'tokio-runtime-worker' panicked at src/scraper/scraper.rs:114:45:
preciazo-scraper-1  | called `Result::unwrap()` on an `Err` value: error returned from database: (code: 5) database is locked
preciazo-scraper-1  | 
preciazo-scraper-1  | Caused by:
preciazo-scraper-1  |     (code: 5) database is locked
preciazo-scraper-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by catdevnull** [comment]
1230f34acaa7bd05023dafd5b1577323d9e9fa91

**Comment by catdevnull** [comment]
parece que finalmente se arregló con https://github.com/catdevnull/preciazo/commit/b843f0ea942288aeeef9dcde24e652327214268f!
